name: 'copy issue'
description: 'Wait a designated number of milliseconds'
inputs:
  githubToken:
    description: "github token"
    required: true
  targetRepository:
    description: 'target repository. format .. owner:repoName'
    required: true
  keyword:
    description: 'keyword which triggers this action'
    default: '/copy'
outputs:
  created: # output will be available to future steps 
    description: 'The created issue'
runs:
  using: 'node12'
  main: 'dist/index.js'