name: 'Github Issue Copier'
description: 'Copy an issue to another repository'
author: 'Soichi Sumi'
inputs:
  githubToken:
    description: "github token"
    required: true
  targetRepository:
    description: 'target repository. format: $OWNER/$REPO_NAME'
    required: true
  keyword:
    description: 'keyword to trigger this action'
    default: '/copy'
outputs:
  created: # output will be available to future steps 
    description: 'The created issue'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'activity'
  color: 'green'